# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anatoliax.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'anatoliax.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61natoliax.proto\x12\tanatoliax\"\x1f\n\rSignalRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"\xaf\x01\n\x0eSignalResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\r\n\x05\x65ntry\x18\x03 \x01(\x01\x12\n\n\x02sl\x18\x04 \x01(\x01\x12\x0b\n\x03tp1\x18\x05 \x01(\x01\x12\x0b\n\x03tp2\x18\x06 \x01(\x01\x12\x0b\n\x03r_r\x18\x07 \x01(\x01\x12\r\n\x05kelly\x18\x08 \x01(\x01\x12\x0e\n\x06regime\x18\t \x01(\t\x12\r\n\x05valid\x18\n \x01(\x08\x12\x0e\n\x06reason\x18\x0b \x01(\t\"H\n\x0bRiskRequest\x12&\n\tpositions\x18\x01 \x03(\x0b\x32\x13.anatoliax.Position\x12\x11\n\tdaily_pnl\x18\x02 \x01(\x01\"T\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x01\x12\x13\n\x0b\x65ntry_price\x18\x03 \x01(\x01\x12\x15\n\rcurrent_price\x18\x04 \x01(\x01\"l\n\x0cRiskResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x18\n\x10max_drawdown_pct\x18\x03 \x01(\x01\x12\x11\n\tdaily_pnl\x18\x04 \x01(\x01\x12\x0e\n\x06regime\x18\x05 \x01(\t\"$\n\rReportRequest\x12\x13\n\x0breport_type\x18\x01 \x01(\t\"i\n\x0eReportResponse\x12\x13\n\x0breport_type\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\t2Q\n\rSignalService\x12@\n\tGetSignal\x12\x18.anatoliax.SignalRequest\x1a\x19.anatoliax.SignalResponse2K\n\x0bRiskService\x12<\n\tCheckRisk\x12\x16.anatoliax.RiskRequest\x1a\x17.anatoliax.RiskResponse2V\n\rReportService\x12\x45\n\x0eGenerateReport\x12\x18.anatoliax.ReportRequest\x1a\x19.anatoliax.ReportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anatoliax_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQUEST']._serialized_start=30
  _globals['_SIGNALREQUEST']._serialized_end=61
  _globals['_SIGNALRESPONSE']._serialized_start=64
  _globals['_SIGNALRESPONSE']._serialized_end=239
  _globals['_RISKREQUEST']._serialized_start=241
  _globals['_RISKREQUEST']._serialized_end=313
  _globals['_POSITION']._serialized_start=315
  _globals['_POSITION']._serialized_end=399
  _globals['_RISKRESPONSE']._serialized_start=401
  _globals['_RISKRESPONSE']._serialized_end=509
  _globals['_REPORTREQUEST']._serialized_start=511
  _globals['_REPORTREQUEST']._serialized_end=547
  _globals['_REPORTRESPONSE']._serialized_start=549
  _globals['_REPORTRESPONSE']._serialized_end=654
  _globals['_SIGNALSERVICE']._serialized_start=656
  _globals['_SIGNALSERVICE']._serialized_end=737
  _globals['_RISKSERVICE']._serialized_start=739
  _globals['_RISKSERVICE']._serialized_end=814
  _globals['_REPORTSERVICE']._serialized_start=816
  _globals['_REPORTSERVICE']._serialized_end=902
# @@protoc_insertion_point(module_scope)
