apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anatoliax-data
  namespace: anatoliax
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
